apiVersion: v1
kind: Service
metadata:
  name: petto-app-service
  labels:
    app: petto
spec:
  type: LoadBalancer
  selector:
    app: petto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376

