version: 2.1
orbs:
  gke: circleci/gcp-gke@1.0.3
  gcr: circleci/gcp-gcr@0.6.1

jobs:
  deploy-image-to-gke:
    steps:
      - gke/rollout-image:
          cluster: $GKE_CLUSTER
          container: petto-app
          deployment: petto-app-deployment
          image: petto-app-image
          tag: $CIRCLE_SHA1

workflows:
  publish-and-deploy:
    jobs:
      - gcr/build-and-push-image:
          image: petto-app-image
          tag: $CIRCLE_SHA1

      - deploy-image-to-gke:
          executor: gke/default
          requires:
            - gcr/build-and-push-image
